server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000
logging:
  level:
    com.bjpn.service.UserService: debug